name: EBAC CI Mobile

on:
  push:
    branches:
      - ci

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout do código
      - uses: actions/checkout@v4

      # Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      # Instalar dependências
      - name: Install dependencies
        run: npm i

      # Rodar os testes
      - name: Run Tests
        run: npm t

      # Publicar o relatório Allure
      - name: Publish Report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report

      # Fazer push das alterações para o repositório
      - name: Push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/qamichaelmaia/application-mobile-test.git
          git add .
          git commit -m "Auto-publish report"
          git push origin ci
